#!/bin/bash
# 环境变量配置功能测试脚本

echo "======================================"
echo "环境变量自动配置功能测试"
echo "======================================"
echo ""

# 检查是否编译成功
if [ ! -f "./debpkg" ]; then
    echo "[INFO] Building debpkg..."
    make clean && make
    if [ $? -ne 0 ]; then
        echo "[ERROR] Build failed!"
        exit 1
    fi
fi

echo "[SUCCESS] Build successful!"
echo ""

# 显示新增的文件
echo "======================================"
echo "新增的模块文件:"
echo "======================================"
ls -lh include/env_config.h src/env_config.c
echo ""

# 查看核心函数
echo "======================================"
echo "env_config.c 核心函数:"
echo "======================================"
grep -E "^int |^void " src/env_config.c | head -n 10
echo ""

# 查看修改的文件
echo "======================================"
echo "修改的文件:"
echo "======================================"
echo "✓ src/install_user.c - 集成环境变量配置检查"
echo ""

# 查看环境变量检测逻辑
echo "======================================"
echo "环境变量检测逻辑:"
echo "======================================"
grep -A 20 "detect_env_issues" src/env_config.c | head -n 25
echo ""

# 查看配置指南
echo "======================================"
echo "环境变量配置指南输出:"
echo "======================================"
grep -A 30 "show_env_config_guide" src/env_config.c | head -n 35
echo ""

# 查看生成的脚本格式
echo "======================================"
echo "生成的环境配置脚本格式:"
echo "======================================"
cat << 'EOF'
#!/bin/bash
# Environment configuration script generated by debpkg
# Source this file to set up environment variables

# Add executables to PATH
export PATH="/home/user/.local/bin:$PATH"

# Add libraries to LD_LIBRARY_PATH
export LD_LIBRARY_PATH="/home/user/.local/lib:$LD_LIBRARY_PATH"

# Add headers to C_INCLUDE_PATH (optional, for development)
export C_INCLUDE_PATH="/home/user/.local/include:$C_INCLUDE_PATH"

# Add man pages to MANPATH (optional)
export MANPATH="/home/user/.local/share/man:$MANPATH"

echo "Environment variables configured successfully!"
EOF
echo ""

# 使用说明
echo "======================================"
echo "使用说明:"
echo "======================================"
echo "1. 安装 DEB 包后会自动检查环境变量配置"
echo "   ./debpkg -u package.deb"
echo ""
echo "2. 如果发现未配置，会提示生成配置脚本"
echo "   输入 'y' 生成 ~/.local/debpkg_env.sh"
echo ""
echo "3. 激活环境变量（二选一）:"
echo "   a) 临时生效：source ~/.local/debpkg_env.sh"
echo "   b) 永久生效：echo 'source \$HOME/.local/debpkg_env.sh' >> ~/.bashrc"
echo "               source ~/.bashrc"
echo ""
echo "4. 验证配置:"
echo "   echo \$PATH"
echo "   echo \$LD_LIBRARY_PATH"
echo ""

echo "======================================"
echo "环境变量说明:"
echo "======================================"
echo "必需的环境变量:"
echo "  ✓ PATH              - 可执行文件搜索路径"
echo "  ✓ LD_LIBRARY_PATH   - 共享库搜索路径"
echo ""
echo "可选的环境变量:"
echo "  ○ C_INCLUDE_PATH    - C/C++ 头文件搜索路径（开发用）"
echo "  ○ MANPATH           - 手册页搜索路径"
echo ""

echo "======================================"
echo "功能特性总结:"
echo "======================================"
echo "✅ 自动检测环境变量配置状态"
echo "✅ 交互式提示和配置建议"
echo "✅ 一键生成统一的配置脚本"
echo "✅ 支持临时和永久两种配置方式"
echo "✅ 一次配置，所有用户目录安装的包都可用"
echo "✅ 不影响系统级安装"
echo ""

echo "======================================"
echo "相关文档:"
echo "======================================"
echo "- ENV_CONFIG_FEATURE.md (详细功能说明)"
echo "- USER_DEPS_FEATURE.md (依赖管理功能)"
echo "- USER_DIRECTORY_INSTALL.md (用户目录安装指南)"
echo ""

echo "======================================"
echo "测试完成!"
echo "======================================"
