/*
 * debpkg - A simple DEB package installer
 * Copyright (C) 2024  debpkg Authors
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#define _GNU_SOURCE
#include "../include/env_config.h"
#include "../include/utils.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

// 检查环境变量是否已配置
static int check_env_var(const char *var_name, const char *search_path) {
    const char *env_value = getenv(var_name);
    
    if (env_value == NULL) {
        return 0;  // 环境变量未设置
    }
    
    // 检查路径是否在环境变量中
    if (strstr(env_value, search_path) != NULL) {
        return 1;  // 已配置
    }
    
    return 0;  // 未配置
}

// 检测是否需要配置环境变量
int detect_env_issues(const char *home_dir) {
    char bin_path[512];
    char lib_path[512];
    char include_path[512];
    char man_path[512];
    int issues = 0;
    
    snprintf(bin_path, sizeof(bin_path), "%s/.local/bin", home_dir);
    snprintf(lib_path, sizeof(lib_path), "%s/.local/lib", home_dir);
    snprintf(include_path, sizeof(include_path), "%s/.local/include", home_dir);
    snprintf(man_path, sizeof(man_path), "%s/.local/share/man", home_dir);
    
    // 检查 PATH
    if (!check_env_var("PATH", bin_path)) {
        issues++;
    }
    
    // 检查 LD_LIBRARY_PATH
    if (!check_env_var("LD_LIBRARY_PATH", lib_path)) {
        issues++;
    }
    
    // 检查 C_INCLUDE_PATH (可选)
    if (is_directory(include_path)) {
        if (!check_env_var("C_INCLUDE_PATH", include_path)) {
            issues++;
        }
    }
    
    // 检查 MANPATH (可选)
    if (is_directory(man_path)) {
        if (!check_env_var("MANPATH", man_path)) {
            issues++;
        }
    }
    
    return issues;
}

// 显示环境变量配置说明
void show_env_config_guide(const char *home_dir) {
    printf("\n");
    print_info("Environment Configuration Guide:");
    printf(COLOR_BLUE "═══════════════════════════════════════════════════════════\n" COLOR_RESET);
    
    printf(COLOR_GREEN "Required Environment Variables:\n" COLOR_RESET);
    printf("  1. PATH - For executable files\n");
    printf("     Add to ~/.bashrc or ~/.zshrc:\n");
    printf("     " COLOR_YELLOW "export PATH=$HOME/.local/bin:$PATH\n" COLOR_RESET);
    printf("\n");
    
    printf("  2. LD_LIBRARY_PATH - For shared libraries\n");
    printf("     Add to ~/.bashrc or ~/.zshrc:\n");
    printf("     " COLOR_YELLOW "export LD_LIBRARY_PATH=$HOME/.local/lib:$LD_LIBRARY_PATH\n" COLOR_RESET);
    printf("\n");
    
    printf(COLOR_GREEN "Optional Environment Variables:\n" COLOR_RESET);
    printf("  3. C_INCLUDE_PATH - For development headers (if needed)\n");
    printf("     Add to ~/.bashrc or ~/.zshrc:\n");
    printf("     " COLOR_YELLOW "export C_INCLUDE_PATH=$HOME/.local/include:$C_INCLUDE_PATH\n" COLOR_RESET);
    printf("\n");
    
    printf("  4. MANPATH - For manual pages (if needed)\n");
    printf("     Add to ~/.bashrc or ~/.zshrc:\n");
    printf("     " COLOR_YELLOW "export MANPATH=$HOME/.local/share/man:$MANPATH\n" COLOR_RESET);
    printf("\n");
    
    printf(COLOR_BLUE "═══════════════════════════════════════════════════════════\n" COLOR_RESET);
    printf(COLOR_YELLOW "[TIP] " COLOR_RESET "Run 'source ~/.bashrc' or 'source ~/.zshrc' after adding these lines.\n");
    printf(COLOR_YELLOW "[TIP] " COLOR_RESET "These settings enable all user-installed packages, not just this one.\n");
    printf("\n");
}

// 生成环境变量配置脚本
int generate_env_script(const char *home_dir, const char *output_path) {
    FILE *fp = fopen(output_path, "w");
    if (fp == NULL) {
        print_error("Failed to create environment script");
        return -1;
    }
    
    fprintf(fp, "#!/bin/bash\n");
    fprintf(fp, "# Environment configuration script generated by debpkg\n");
    fprintf(fp, "# Source this file to set up environment variables\n");
    fprintf(fp, "\n");
    fprintf(fp, "# Add executables to PATH\n");
    fprintf(fp, "export PATH=\"%s/.local/bin:$PATH\"\n", home_dir);
    fprintf(fp, "\n");
    fprintf(fp, "# Add libraries to LD_LIBRARY_PATH\n");
    fprintf(fp, "export LD_LIBRARY_PATH=\"%s/.local/lib:$LD_LIBRARY_PATH\"\n", home_dir);
    fprintf(fp, "\n");
    fprintf(fp, "# Add headers to C_INCLUDE_PATH (optional, for development)\n");
    fprintf(fp, "export C_INCLUDE_PATH=\"%s/.local/include:$C_INCLUDE_PATH\"\n", home_dir);
    fprintf(fp, "\n");
    fprintf(fp, "# Add man pages to MANPATH (optional)\n");
    fprintf(fp, "export MANPATH=\"%s/.local/share/man:$MANPATH\"\n", home_dir);
    fprintf(fp, "\n");
    fprintf(fp, "echo \"Environment variables configured successfully!\"\n");
    
    fclose(fp);
    
    // 设置可执行权限
    chmod(output_path, 0755);
    
    print_success("Environment script created: ");
    printf("%s\n", output_path);
    
    return 0;
}

// 检查并提示环境变量配置
int check_and_prompt_env_config(const char *home_dir, const char *pkg_name) {
    char bin_path[512];
    char lib_path[512];
    char config_script[512];
    int needs_config = 0;
    
    snprintf(bin_path, sizeof(bin_path), "%s/.local/bin", home_dir);
    snprintf(lib_path, sizeof(lib_path), "%s/.local/lib", home_dir);
    snprintf(config_script, sizeof(config_script), "%s/.local/debpkg_env.sh", home_dir);
    
    // 检测环境变量问题
    int issues = detect_env_issues(home_dir);
    
    if (issues > 0) {
        printf("\n");
        print_warning("Environment variables may need configuration!");
        printf(COLOR_YELLOW "[INFO] " COLOR_RESET "%d environment variable(s) need attention.\n", issues);
        printf("\n");
        
        // 检查是否已生成过配置脚本
        if (!file_exists(config_script)) {
            printf("Do you want to generate an environment configuration script? (y/n): ");
            
            char choice;
            if (scanf(" %c", &choice) != 1) {
                print_error("Invalid input");
                return -1;
            }
            
            if (choice == 'y' || choice == 'Y') {
                if (generate_env_script(home_dir, config_script) == 0) {
                    printf("\n");
                    print_info("To activate the environment variables, run:");
                    printf(COLOR_GREEN "  source %s\n" COLOR_RESET, config_script);
                    printf("\n");
                    printf("Or add the following lines to your ~/.bashrc or ~/.zshrc:\n");
                    printf(COLOR_YELLOW "  source $HOME/.local/debpkg_env.sh\n" COLOR_RESET);
                    printf("\n");
                }
            }
        } else {
            print_info("Environment script already exists:");
            printf(COLOR_GREEN "  %s\n" COLOR_RESET, config_script);
            printf("\n");
            printf("To activate, run:\n");
            printf(COLOR_GREEN "  source %s\n" COLOR_RESET, config_script);
            printf("\n");
        }
        
        // 显示详细配置指南
        printf("Would you like to see detailed environment configuration guide? (y/n): ");
        
        char show_guide;
        if (scanf(" %c", &show_guide) != 1) {
            return -1;
        }
        
        if (show_guide == 'y' || show_guide == 'Y') {
            show_env_config_guide(home_dir);
        }
    } else {
        print_success("All environment variables are properly configured!");
    }
    
    return 0;
}
